# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://mypsyhealth.ru" # the base hostname & protocol for your site
title: ЦЕНТР ПСИХИЧЕСКОГО ЗДОРОВЬЯ И АНОНИМНОЙ ПОМОЩИ МАЙПСИХЕЛС - MYPSYHEALTH В МОСКВЕ
build: 3
email: mypsyhealthnew@gmail.com
phone: +7 (495) 150-53-05
phone_e164: +74951505305
timezone: Europe/Moscow

legal:
  name: Профессиональная медицина
  reg_no:
  license_no: ЛО-50-01-007268

social:
  fb: https://www.facebook.com/groups/353782178382721/?ref=bookmarks
  vk: https://vk.com/psyhohealth
  ok: https://ok.ru/psyhohealth
  insta: https://www.instagram.com/mypsyhohealth

description: >- # this means to ignore newlines until "baseurl:"
  Центр психического здоровья и анонимной помощи Майпсихелс - Mypsyhealth в Москве. Частная наркологическая, психиатрическая, неврологическая и психологическая помощь. Работаем круглосуточно.
baseurl: "/docker-jekyll-audasitey" # the subpath of your site, e.g. /blog
#twitter_username: jekyllrb
#github_username:  jekyll
paginate: 5 # !!!!!!!!!!! no change after search indexing
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  # - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-compress-images

#compress_images:
#  images_path: "img/**/*.{gif,png,jpg,jpeg,svg}"
#feed:
#  posts_limit: 20
#  excerpt_only: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [ '_site', 'node_modules', '.ssh', '_logs', '.sass-cache', '.env', '_docker' ]
