# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
​
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Audacity site
description: >- # this means to ignore newlines until "baseurl:"
  Audacity site
url: "https://dilsonspickles.github.io" # the base hostname & protocol for your site
build: 3
email: www.audacityteam.org@gmail.com
phone: +7 (495) 150-53-05
phone_e164: +74951505305
timezone: Europe/London
​
legal:
  name: Audacity
​
social:
  fb: https://www.facebook.com/groups/audacity
  vk: https://vk.com/audacity
  ok: https://ok.ru/audacity
  insta: https://www.instagram.com/audacity

#twitter_username: jekyllrb
#github_username:  jekyll
paginate: 5 # !!!!!!!!!!! no change after search indexing
paginate_path: "/blog/page:num/"
​
# Build settings
markdown: kramdown
theme: minima
plugins:
  # - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-compress-images
​
#compress_images:
#  images_path: "img/**/*.{gif,png,jpg,jpeg,svg}"
#feed:
#  posts_limit: 20
#  excerpt_only: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [ '_site', 'node_modules', '.ssh', '_logs', '.sass-cache', '.env']